name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [8.3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, curl, json
          coverage: none

      - name: Install Composer dependencies
        run: |
          composer install --prefer-dist --no-interaction --no-progress

      - name: Run PHPUnit tests
        run: |
          vendor/bin/phpunit --configuration phpunit.xml.dist

      - name: Lint PHP files
        run: |
          # Optional: run PHP CodeSniffer if configured
          if [ -f phpcs.xml.dist ]; then
            vendor/bin/phpcs --standard=phpcs.xml.dist .
          fi
